// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Http$ReasonLambda = require("./Http.bs.js");

function test(json) {
  return /* record */[
          /* userId */Json_decode.field("userId", Json_decode.$$int, json),
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* body */Json_decode.field("body", Json_decode.string, json)
        ];
}

var Decode = /* module */[/* test */test];

function handler($$event, _, callback) {
  var event2 = Caml_array.caml_array_get($$event.Record, 0).EventSource;
  console.log("Hello, BuckleScript and Reason!" + event2);
  return Curry._2(Http$ReasonLambda.Client[/* get */0], "https://play.google.com/log?format=json", (function () {
                Curry._1(callback, Js_exn.raiseError("WAZAAA"));
                return Curry._1(callback, null);
              }));
}

Curry._2(Http$ReasonLambda.Client[/* get */0], "http://jsonplaceholder.typicode.com/posts/1", (function (response) {
        var results = /* array */[];
        return Curry._2(Http$ReasonLambda.IncomingMessage[/* on */0], response, /* `data */[
                    -1033677270,
                    (function (data) {
                        var results$1 = $$Array.append(results, /* array */[data]);
                        return Curry._2(Http$ReasonLambda.IncomingMessage[/* on */0], response, /* `_end */[
                                    1058556124,
                                    (function () {
                                        console.log(results$1.concat().toString());
                                        return /* () */0;
                                      })
                                  ]);
                      })
                  ]);
      }));

exports.Decode = Decode;
exports.handler = handler;
/*  Not a pure module */
