// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Http = require("http");

var IncomingMessage = /* module */[/* on */(function (prim, prim$1) {
      prim.on((function () {
                switch (prim$1[0]) {
                  case 1058556124 : 
                      return "end";
                  case -1033677270 : 
                      return "data";
                  
                }
              })(), prim$1[1]);
      return /* () */0;
    })];

var Client = /* module */[/* get */(function (prim, prim$1) {
      Http.get(prim, prim$1);
      return /* () */0;
    })];

exports.IncomingMessage = IncomingMessage;
exports.Client = Client;
/* http Not a pure module */
