// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Http = require("http");

function IncomingMessage_000(prim, prim$1, prim$2) {
  prim.on((function () {
            switch (prim$1) {
              case 758940234 : 
                  return "data";
              
            }
          })(), prim$2);
  return /* () */0;
}

function IncomingMessage_001(prim, prim$1, prim$2) {
  prim.on((function () {
            switch (prim$1) {
              case 758940234 : 
                  return "data";
              
            }
          })(), prim$2);
  return /* () */0;
}

var IncomingMessage = /* module */[
  IncomingMessage_000,
  IncomingMessage_001
];

var Client = /* module */[/* get */(function (prim, prim$1) {
      Http.get(prim, prim$1);
      return /* () */0;
    })];

exports.IncomingMessage = IncomingMessage;
exports.Client = Client;
/* http Not a pure module */
